### ISSUE TITLE
jacocoagent.jar 插桩报错

### ISSUE THREAD

**Issue by 666-code** [alwans/code-diff#4]
java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_a5cf5b3/core/runtime/ChainNodeHandle

**Comment by alwans** [comment]
jdk版本多少

**Comment by 666-code** [comment]
是1.8




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alwans/code-diff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月27日(星期三) 上午9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alwans/code-diff] jacocoagent.jar 插桩报错 (Issue #4)





 
jdk版本多少

**Comment by alwans** [comment]
java -javaagent:jacocoagent.jar=includes=*com.test.jvm.*,output=tcpserver,address=127.0.0.1,port=3306,append=false,branchName=test,commitId=123456 -jar xxx.jar
com.test.jvm改成你服务的包名
xxx.jar 就是你服务jar
我自己测试了下，写了includes就没问题，应该是我的改动对底层一些类有一些影响，暂时要先屏蔽掉，后期我再优化这这里

**Comment by alwans** [comment]
java -javaagent:jacocoagent.jar=includes=*com.test.jvm.*,output=tcpserver,address=127.0.0.1,port=3306,append=false,branchName=test,commitId=123456 -jar xxx.jar
com.test.jvm改成你服务的包名
xxx.jar 就是你服务jar
我自己测试了下，写了includes就没问题，应该是我的改动对底层一些类有一些影响，暂时要先屏蔽掉，后期我再优化这这里

**Comment by alwans** [comment]
java -javaagent:jacocoagent.jar=includes=*com.test.jvm.*,output=tcpserver,address=127.0.0.1,port=3306,append=false,branchName=test,commitId=123456 -jar xxx.jar
com.test.jvm改成你服务的包名
xxx.jar 就是你服务jar
我自己测试了下，写了includes就没问题，应该是我的改动对底层一些类有一些影响，暂时要先屏蔽掉，后期我再优化这这里

**Comment by alwans** [comment]
java -javaagent:jacocoagent.jar=includes=*com.test.jvm.*,output=tcpserver,address=127.0.0.1,port=3306,append=false,branchName=test,commitId=123456 -jar xxx.jar
【com.test.jvm.】改成你服务的包名；记得前后加个星号，github上我写了，但是保存后就没了
xxx.jar 就是你服务jar
我自己测试了下，写了includes就没问题，应该是我的改动对底层一些类有一些影响，暂时要先屏蔽掉，后期我再优化这这里

**Comment by 666-code** [comment]
生成增量报告的时候com.test.diff.services.internal.jacoco的report方法报null，方便加个vx不？vx:FUPOliuhui
