### ISSUE TITLE
jacoco-cli.jar 生产报告时提示 Unrecognized token 'code': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"code.json"; line: 1, column: 5]

### ISSUE THREAD

**Issue by zspandy** [alwans/code-diff#7]
![1](https://user-images.githubusercontent.com/49773359/205619630-24ed2043-41ee-44fe-a1bb-aaf466ffa2c9.png)

![2](https://user-images.githubusercontent.com/49773359/205620144-44bd852b-6677-4627-9607-3e474c920efc.png)

大佬可以分享一下 jacoco-cli的源码？

**Comment by alwans** [comment]
这不是用的我的cli包吧？
@Option(name = "--diffFiles", usage = "Code difference collection", metaVar = "<charset>")
String diffFiles;
我没写支持传json文件的

**Comment by zspandy** [comment]
![image](https://user-images.githubusercontent.com/49773359/205691764-c32d1b06-8dcd-43a2-9cc7-42d86ec7e31c.png)
![image](https://user-images.githubusercontent.com/49773359/205692009-3e0dbfaf-84f8-4436-a6de-efdb1bcb3a11.png
嗯嗯  但是我单独把您这边不同commitid生成的diffCode的那个方法单独拎出来生成json字符串  然后在手动用您项目下的lib包下jacoco-cli.jar包去生产报告就提示上面的错
[aa.txt](https://github.com/alwans/code-diff/files/10156120/aa.txt)

**Comment by alwans** [comment]
json字符串加上双引号或者单引号试试

**Comment by zspandy** [comment]
一.附件中aa.txt中差异文件是单独执行您这个方法返回生产的， 我拿了其中一个类的差异执行了上面的那个命令的













二.我执行您项目中生产报告的方法，貌似也是报错了， 没有走到debugger








三.其实我现在的主要需求是一个项目版本多次重复部署后， 想解决多次发布后exec合并生成一个总的测试报告的一个需求， 方便加一个大佬您的微信或者QQ？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alwans/code-diff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alwans/code-diff] jacoco-cli.jar 生产报告时提示 Unrecognized token 'code': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"code.json"; line: 1, column: 5] (Issue #7)





 
json字符串加上双引号或者单引号试试

**Comment by zspandy** [comment]
隐藏

**Comment by zspandy** [comment]
> <img alt="@zspandy" width="20" height="20" src="https://avatars.githubusercontent.com/u/49773359?s=40&amp;v=4">



> 了，调试器。。还是QQ？
> [……](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alwans/code-diff" ***@***.***&gt;; 发送时间:&nbsp;2022年12月6日(星期二) 上午10:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alwans/code-diff] jacoco-cli.jar 生产报告时提示 Unrecognized token 'code': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (String)"code.json"; line: 1, column: 5] (Issue #7) json字符串加上双引号或者单引号试试 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



> 了，调试器。。还是QQ？
> [……](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alwans/code-diff" ***@***.***&gt;; 发送时间:&nbsp;2022年12月6日(星期二) 上午10:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alwans/code-diff] jacoco-cli.jar 生产报告时提示 Unrecognized token 'code': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (String)"code.json"; line: 1, column: 5] (Issue #7) json字符串加上双引号或者单引号试试 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
