### ISSUE TITLE
内部类和匿名内部类的覆盖率合并处理

### ISSUE THREAD

**Issue by weijie-xiao** [alwans/code-diff#9]
楼主好！我这边目前遇到代码文件中内部类和匿名类的覆盖率合并的问题？想请教下怎么处理比较好？

1. 内部类的，
`
public class AnonymousClassTest {
    public class InnerClass {
        public int sum(int a, int b){
            return a + b;
        }
`
合并 sum 方法的时候因为解析的 classInfo.className 是 AnonymousClassTest， 按照目前逻辑会获取 AnonymousClassTest.class 进行分析，但是 sum 方法的插桩信息实际需要根据 AnonymousClassTest$InnerClass.class 来解析，会导致 sum 方法的覆盖率没有合并到。
想法：打算在解析 methodInfo 的时候记录下来方法真正所属的类。然后可以根据 AnonymousClassTest$InnerClass 去找 class 文件来解析合并

2. 匿名类的，
匿名类的名称并不固定，而且 classId 等信息也可能会变化，
请问能有什么方式准确拿到新旧 class 的对应关系吗？

---------------------------------------------------------

抱歉，现在才看到testerhome上的回复。看到评论被禁掉了，所以来git上留个言，微信 wj31673

**Comment by alwans** [comment]
内部类和匿名类问题都进行了优化，思路和你是相同的。但是对于匿名类特殊情况没做处理：例如同一个方法在多个匿名内部类中存在，这种情况暂时也没有好的处理思路
